services:
  - type: web
    name: network-security-api
    runtime: docker
    repo: https://github.com/Sahilpatil009/network-security-edi.git
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URL_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
